repoUrl: "https://github.com/deverton/argocd-demo.git"
targetRevision: HEAD
region: ""
account: ""
clusterName: ""

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  serviceAccountName:

# Cluster Autoscaler Values
clusterAutoscaler:
  serviceAccountName:
