repoUrl: "https://github.com/deverton/argocd-demo.git"
targetRevision: HEAD
region: ""
account: ""
clusterName: ""

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:

# Metrics Server Values
metricsServer:
  enable: false
