---
apiVersion: v1
kind: Secret
metadata:
  name: argoproj-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: argoproj-argocd
  url: https://argoproj.github.io/argo-helm
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: prometheus-argocd
  url: https://prometheus-community.github.io/helm-charts
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: grafana-argocd
  url: https://grafana.github.io/helm-charts
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: crossplane-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: crossplane-argocd
  url: https://charts.crossplane.io/stable
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: eks-charts-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: eks-charts-argocd
  url: https://aws.github.io/eks-charts
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: projectcalico-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: projectcalico-argocd
  url: https://docs.projectcalico.org/charts
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: autoscaler-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: autoscaler-argocd
  url: https://kubernetes.github.io/autoscaler
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: metrics-server-argocd
  url: https://kubernetes-sigs.github.io/metrics-server
  type: helm
