apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.4.2
    helm: 
      parameters:
      - name: clusterName
        value: {{ .Values.clusterName }}
      - name: region
        value: {{ .Values.region }}
      - name: serviceAccount.name
        value: {{ .Values.awsLoadBalancerController.serviceAccountName }}
      values: |
        serviceAccount:
          create: false
        # Required to when running Calico
        # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1591#issuecomment-721846527
        hostNetwork: true
        replicaCount: 1
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  