apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: https://docs.projectcalico.org/charts
    chart: tigera-operator
    targetRevision: v3.21.4
    values: |
      installation:
        kubernetesProvider: "EKS"
  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
