apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.15.0
    helm: 
      parameters:
      - name: awsRegion
        value: {{ .Values.region }}
      - name: rbac.serviceAccount.name
        value: {{ .Values.clusterAutoscaler.serviceAccountName }}
      - name: autoDiscovery.clusterName
        value: {{ .Values.clusterName }}
      values: |
        expanderPriorities:
          100:
            - .*-spot-.*
          10:
            - .*

        extraArgs:
          aws-use-static-instance-list: true
          expander: "priority"

        rbac:
          serviceAccount:
            create: false

        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
