apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-provisioners
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/provisioners
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
      - name: clusterName
        value: {{ .Values.clusterName }}
      values: |
        {{- if .Values.karpenterProvisioners.azs }}
        azs:
          {{ .Values.karpenterProvisioners.azs | fromYaml }}
        {{- end}}
        {{- if .Values.karpenterProvisioners.tags }}
        tags:
          {{ .Values.karpenterProvisioners.tags | fromYaml }}
        {{- end}}
        {{- if .Values.karpenterProvisioners.subnetSelectors }}
        subnetSelectors:
          {{ .Values.karpenterProvisioners.subnetSelectors | fromYaml }}
        {{- end}}
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
