apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: "https://charts.karpenter.sh"
    chart: karpenter
    targetRevision: "0.10.1"
    helm:
      parameters:
        - name: serviceAccount.name
          value: {{ .Values.karpenter.serviceAccountName }}
        - name: clusterName
          value: {{ .Values.clusterName }}
        - name: clusterEndpoint
          value: {{ .Values.karpenter.controllerClusterEndpoint }}
        - name: aws.defaultInstanceProfile
          value: {{ .Values.karpenter.awsDefaultInstanceProfile }}
      values: |
        serviceAccount:
          create: false
        nodeSelector:
          kubernetes.io/os: linux
  destination:
    name: in-cluster
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
