apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: "https://charts.karpenter.sh"
    chart: karpenter
    targetRevision: "0.9.1"
    helm:
      parameters:
        - name: karpenter.serviceAccount.name
          value: {{ .Values.karpenter.serviceAccountName }}
        - name: karpenter.clusterName
          value: {{ .Values.clusterName }}
        - name: karpenter.clusterEndpoint
          value: {{ .Values.karpenter.controllerClusterEndpoint }}
        - name: karpenter.aws.defaultInstanceProfile
          value: {{ .Values.karpenter.awsDefaultInstanceProfile }}
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
