apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    {{- if .Values.azs }}
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        {{- range .Values.azs }}
        - {{ . }}  
        {{- end}}
    {{- end }}
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - m5.large
        - m5.xlarge
        - m5.2xlarge
        - c5.large
        - c5.xlarge
        - c5a.large
        - c5a.xlarge
        - r5.large
        - r5.xlarge
  limits:
    resources:
      cpu: 1k
  provider:
    {{- if .Values.subnetSelectors }}
    subnetSelector:
      {{ toYaml .Values.subnetSelectors | indent 6 }}
    {{- end }}
    securityGroupSelector:
      karpenter.sh/discovery/{{ .Values.clusterName }}: {{ .Values.clusterName }}
    {{- if .Values.tags }}
    tags:
    {{ toYaml .Values.tags | indent 4 }}
    {{- end }}
  # If nil, the feature is disabled, nodes will never expire
  ttlSecondsUntilExpired: 2592000 # 30 Days = 60 * 60 * 24 * 30 Seconds;
  # If nil, the feature is disabled, nodes will never scale down due to low utilization
  ttlSecondsAfterEmpty: 30
