apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    {{- if .Values.azs }}
    - key: topology.kubernetes.io/zone
      operator: In
      values: {{ .Values.azs }}
    {{- end }}
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: {{ .Values.instanceProfile }}
    {{- if .Values.subnetSelectors }}
    subnetSelector:
      {{ toYaml .Values.subnetSelectors | indent 6 }}
    {{- end }}
    securityGroupSelector:
      karpenter.sh/discovery/{{ .Values.clusterName }}: {{ .Values.clusterName }}
    {{- if .Values.tags }}
    tags:
    {{ toYaml .Values.tags | indent 4 }}
    {{- end }}
  ttlSecondsAfterEmpty: 30
