expanderPriorities:
  100:
    - .*-spot-.*
  10:
    - .*

extraArgs:
  aws-use-static-instance-list: true
  expander: "priority"

rbac:
  serviceAccount:
    create: false

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
